/* Javascript library containing avatar list for MMBN2 */
mmbn2de.avatars = {
	'0 64': 'megaman', '0 0': 'lan', '0 7': 'mayl',
	'0 9': 'mina-laytonica', '0 8': 'moleque-sapao', '0 1': 'yai',
	'0 2': 'dex', '0 3': 'mari', '0 18': 'quarentao-assalariado',
	'0 10': 'pirralho-testudo', '0 16': 'patricinha-rosa',
	'0 26': 'pirralho-bone', '0 15': 'grandao-frankenstein',
	'0 19': 'vovozinha-sapao', '0 39': 'morenao-laranja', '0 38': 'arashi',
	'0 14': 'mulher-gordona', '0 11': 'mae-lan', '0 66': 'programa-verde',
	'0 71': 'navi-roxo-mal', '0 76': 'gutsman', '0 69': 'roll',
	'???': 'glyde',
	'0 22': 'cientista-generico',
	'???': 'airman',
	'???': 'homem-desconhecido',
	'0 13': 'velhinho-chapeu',
	'0 17': 'pirralhinha-chuquinha',
	'0 20': 'carinha-metro',
	'0 25': 'maid-avental',
	'0 37': 'secretaria-cabelo-curto',
	'0 49': 'loirao-topetudo',
	'0 41': 'ribitta',
	'0 42': 'cameraman',
	'0 36': 'guile-velho',
	'0 74': 'protoman',
	'0 6': 'chaud',
	'0 34': 'mina-cachecol',
	'0 30': 'fortao-bandana',
	'???': 'speedy-dave',
	'???': 'quickman',
	'???': 'kingman',
	'???': 'cutman',
	'0 23': 'pai-lan',
	'0 53': 'assistente-loirao',
	'???': 'aeromoca',
	'0 29': 'mina-albina',
	'0 46': 'vendedor-gravata',
	'0 44': 'vendedora-gravata',
	'0 51': 'nega-brinco-azul',
	'0 47': 'loirao-serio',
	'0 45': 'loirinha-gravata',
	'???': 'brutamontes-oculos',
	'0 52': 'nego-zoin',
	'0 50': 'negao-bombado',
	'0 48': 'velha-nariguda',
	'0 55': 'raoul',
	'???': 'sr-higsby',
	'0 56': 'sra-millions',
	'???': 'numberman',
	'???': 'princesa-pride',
	'0 61': 'gauss',
	'0 40': 'sean',
	'0 62': 'careca-laytonico',
	'0 59': 'piloto-com-oculos',
	'0 60': 'piloto-sem-oculos',
	'???': 'magnetman',
	'0 12': 'mr-match',
	'???': 'freezeman',
	'???': 'sr-famoso',
	'0 70': 'navi-verde',
	'2 1': 'navi-roxo',
	'???': 'navi-mal',
	'0 73': 'navi-ciclope',
	'???': 'shadowman',
	'???': 'operador-shadowman',
	'???': 'escuridao',
	'???': 'knightman',
	'???': 'lord-gospel',
	'0 90': 'bass',
	'???': 'pharaohman',
	'???': 'napalmman',
	'???': 'wall-e'
}